name: Deployment

on:
  deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./build/
        name: build

    - name: Deploy
      env:
        DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
        RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
      run: rsync -avHz --ignore-times build/ $DEPLOY_TARGET

    - name: Create Github Deployment Status
      uses: unacast/actions-github-deployment-status@v0.3.0
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
