name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --unshallow --tags

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./build/
        name: build

    - name: Start deployment
      uses: chrnorm/deployment-action@v1.2.0
      id: deployment
      with:
        token: "${{ github.token }}"
        environment: production

    - name: Deploy
      env:
        DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
        RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
      run: rsync -avHz --ignore-times build/ $DEPLOY_TARGET

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v1.0.0
      with:
        token: "${{ github.token }}"
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v1.0.0
      with:
        token: "${{ github.token }}"
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
